import { 
  LayoutDashboard, 
  Radio, 
  FileText, 
  Building2, 
  Scale, 
  Stethoscope, 
  Wrench,
  Search,
  Bell,
  Settings,
  LogOut,
  User,
  LogIn,
  UserPlus,
  Briefcase,
  ScrollText
} from 'lucide-react';
import { NavItem, TranslationDictionary } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  searchPlaceholder: { bn: 'অনুসন্ধান করুন...', en: 'Search...' },
  welcome: { bn: 'স্বাগতম', en: 'Welcome' },
  dashboard: { bn: 'ড্যাশবোর্ড', en: 'Dashboard' },
  liveReports: { bn: 'লাইভ রিপোর্ট', en: 'Live Reports' },
  projectProposals: { bn: 'প্রকল্প প্রস্তাবনা', en: 'Project Proposals' },
  govtProjects: { bn: 'সরকারি প্রকল্প', en: 'Govt Projects' },
  integrityIndex: { bn: 'সততা সূচক', en: 'Integrity Index' },
  hospitals: { bn: 'হাসপাতাল', en: 'Hospitals' },
  communityRepair: { bn: 'কমিউনিটি মেরামত', en: 'Community Repair' },
  tenderAnalysis: { bn: 'টেন্ডার বিশ্লেষণ', en: 'Tender Analysis' },
  footerDisclaimer: { bn: '© ২০২৪ নাগরিক সেবা। সর্বস্বত্ব সংরক্ষিত।', en: '© 2024 Nagorik Seba. All rights reserved.' },
  activeProjects: { bn: 'সক্রিয় প্রকল্প', en: 'Active Projects' },
  resolvedIssues: { bn: 'মীমাংসিত সমস্যা', en: 'Resolved Issues' },
  pendingReports: { bn: 'অপেক্ষমান রিপোর্ট', en: 'Pending Reports' },
  satisfactionRate: { bn: 'সন্তোষের হার', en: 'Satisfaction Rate' },
  citizenEngagement: { bn: 'নাগরিক অংশগ্রহণ', en: 'Citizen Engagement' },
  monthlyTrend: { bn: 'মাসিক প্রবণতা', en: 'Monthly Trend' },
  recentActivity: { bn: 'সাম্প্রতিক কার্যকলাপ', en: 'Recent Activity' },
  profile: { bn: 'প্রোফাইল', en: 'Profile' },
  settings: { bn: 'সেটিংস', en: 'Settings' },
  logout: { bn: 'লগ আউট', en: 'Log Out' },
  login: { bn: 'প্রবেশ করুন', en: 'Login' },
  signup: { bn: 'নিবন্ধন করুন', en: 'Sign Up' },
  mobileNumber: { bn: 'মোবাইল নম্বর', en: 'Mobile Number' },
  nidNumber: { bn: 'জাতীয় পরিচয়পত্র (NID)', en: 'NID Number' },
  password: { bn: 'পাসওয়ার্ড', en: 'Password' },
  verifyIdentity: { bn: 'পরিচয় যাচাই করুন', en: 'Verify Identity' },
  secureNote: { bn: 'আপনার পরিচয় এনক্রিপ্টেড থাকবে। পাবলিকভাবে কখনো দেখানো হবে না।', en: 'Your identity is encrypted and will never be shown publicly.' },
  otpTitle: { bn: 'যাচাইকরণ কোড', en: 'Verification Code' },
  otpSent: { bn: 'আপনার মোবাইলে ৬ সংখ্যার কোড পাঠানো হয়েছে', en: 'A 6-digit code has been sent to your mobile' },
  resend: { bn: 'পুনরায় পাঠান', en: 'Resend' },
  verify: { bn: 'যাচাই করুন', en: 'Verify' },
  oathTitle: { bn: 'নৈতিক শপথ', en: 'Ethical Oath' },
  oathText: { bn: 'আমি শপথ করছি যে, আমি সর্বদা সত্য বলব, কাউকে মিথ্যা অপবাদ দেব না এবং দেশের কল্যাণে এই প্ল্যাটফর্ম ব্যবহার করব।', en: 'I pledge to speak the truth, never slander anyone, and use this platform for the welfare of the country.' },
  iAgree: { bn: 'আমি সম্মত', en: 'I Agree' },
  continue: { bn: 'সামনে এগিয়ে যান', en: 'Continue' },
  congratulations: { bn: 'অভিনন্দন!', en: 'Congratulations!' },
  verifiedCitizen: { bn: 'যাচাইকৃত নাগরিক', en: 'Verified Citizen' },
  trustScore: { bn: 'ট্রাস্ট স্কোর', en: 'Trust Score' },
  publicProfile: { bn: 'আপনার পাবলিক প্রোফাইল', en: 'Your Public Profile' },
  generatedId: { bn: 'নাগরিক আইডি', en: 'Citizen ID' },
  backToLogin: { bn: 'লগিন এ ফিরে যান', en: 'Back to Login' },
  
  // Report Card Translations
  truthProbability: { bn: 'সত্যতার সম্ভাবনা', en: 'Truth Probability' },
  truthTooltip: { bn: 'এই স্কোর AI ও মানুষের যাচাই থেকে তৈরি।', en: 'Score generated from AI and human verification.' },
  weightedSupport: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Support' },
  support: { bn: 'সমর্থন করি', en: 'Support' },
  doubt: { bn: 'সন্দেহ আছে', en: 'Doubt' },
  aiBreakdown: { bn: 'AI বিশ্লেষণ', en: 'AI Analysis' },
  credibility: { bn: 'সমর্থনকারীদের বিশ্বাসযোগ্যতা', en: 'Supporter Credibility' },
  evidenceQuality: { bn: 'প্রমাণের মান', en: 'Evidence Quality' },
  mediaCheck: { bn: 'মিডিয়া যাচাই', en: 'Media Check' },
  historyMatch: { bn: 'আগের মিল থাকা কেস', en: 'Historical Match' },
  readMore: { bn: 'আরও পড়ুন', en: 'Read More' },
  showLess: { bn: 'কমিয়ে দেখুন', en: 'Show Less' },
  status_review: { bn: 'পর্যালোচনাধীন', en: 'Under Review' },
  status_verified: { bn: 'যাচাইকৃত', en: 'Verified' },
  status_disputed: { bn: 'বিতর্কিত', en: 'Disputed' },
  anonymous: { bn: 'বেনামী', en: 'Anonymous' },
  evidence: { bn: 'প্রমাণসমূহ', en: 'Evidence' },
  
  // Tabs
  tab_discussion: { bn: 'আলোচনা', en: 'Discussion' },
  tab_evidence: { bn: 'অতিরিক্ত প্রমাণ', en: 'Add Evidence' },
  tab_timeline: { bn: 'টাইমলাইন', en: 'Timeline' },
  
  // Discussion
  sort_trusted: { bn: 'বিশ্বস্ত', en: 'Most Trusted' },
  sort_recent: { bn: 'সাম্প্রতিক', en: 'Recent' },
  local_resident: { bn: 'স্থানীয়', en: 'Local' },
  agree: { bn: 'সহমত', en: 'Agree' },
  disagree: { bn: 'অসম্মত', en: 'Disagree' },
  reply: { bn: 'রিপ্লাই', en: 'Reply' },
  filter_local_only: { bn: 'শুধুমাত্র স্থানীয়', en: 'Local Only' },
  filter_expert_only: { bn: 'শুধুমাত্র বিশেষজ্ঞ', en: 'Experts Only' },
  
  // Badges & Impact
  badge_engineer: { bn: 'প্রকৌশলী', en: 'Engineer' },
  badge_doctor: { bn: 'ডাক্তার', en: 'Doctor' },
  badge_lawyer: { bn: 'আইনজীবী', en: 'Lawyer' },
  badge_accountant: { bn: 'অ্যাকাউন্ট্যান্ট', en: 'Accountant' },
  verified_area: { bn: 'এই এলাকায় যাচাইকৃত', en: 'Verified in this area' },
  impact_weight: { bn: 'বর্তমান প্রভাব ওজন', en: 'Current Impact Weight' },
  verification_tooltip: { bn: 'এই তথ্য ভেরিফিকেশনের মাধ্যমে নিশ্চিত করা হয়েছে', en: 'This information has been confirmed via verification' },

  // Evidence Upload
  dragDrop: { bn: 'ছবি বা ভিডিও এখানে ড্রপ করুন', en: 'Drop photos or videos here' },
  addDesc: { bn: 'বিবরণ যোগ করুন...', en: 'Add a description...' },
  submitEvidence: { bn: 'প্রমাণ জমা দিন', en: 'Submit Evidence' },
  
  // Timeline events
  event_created: { bn: 'রিপোর্ট তৈরি হয়েছে', en: 'Report Created' },
  event_ai_check: { bn: 'AI যাচাইকরণ সম্পন্ন', en: 'AI Verification Complete' },
  event_evidence: { bn: 'নতুন প্রমাণ যুক্ত হয়েছে', en: 'New Evidence Added' },
  event_review: { bn: 'মডারেটর রিভিউ', en: 'Moderator Review' },
  
  // Influence Monitoring Panel
  influencePanel: { bn: 'ইনফ্লুয়েন্স মনিটরিং প্যানেল', en: 'Influence Monitoring Panel' },
  risk_high: { bn: 'উচ্চ ঝুঁকি', en: 'High Risk' },
  risk_medium: { bn: 'মাঝারি ঝুঁকি', en: 'Medium Risk' },
  risk_low: { bn: 'কম ঝুঁকি', en: 'Low Risk' },
  coordinatedEffort: { bn: 'সম্ভাব্য সমন্বিত প্রচেষ্টা শনাক্ত', en: 'Potential Coordinated Effort Detected' },
  voteSpike: { bn: 'ভোট বৃদ্ধি', en: 'Vote Spike' },
  abnormalSpike: { bn: 'এই সময়ে অস্বাভাবিক ভোট বৃদ্ধি হয়েছে', en: 'Abnormal vote spike detected at this time' },
  geoCluster: { bn: 'ভৌগোলিক ক্লাস্টার বিশ্লেষণ', en: 'Geographic Cluster Analysis' },
  aiExplanation: { bn: 'একই সময়ে নতুন অ্যাকাউন্ট থেকে বহু সমর্থন আসায় কিছু ভোটের ওজন কমানো হয়েছে।', en: 'Some vote weights were reduced due to multiple supports from new accounts at the same time.' },
  transparencyNote: { bn: 'এই বিশ্লেষণ স্বয়ংক্রিয় AI দ্বারা করা হয়েছে এবং মানব মডারেটর পর্যালোচনা করতে পারে।', en: 'This analysis was done by automated AI and may be reviewed by human moderators.' },

  // Project Proposals
  aiSimpleExplain: { bn: 'AI সহজ ভাষায় ব্যাখ্যা', en: 'AI Simplified Explanation' },
  govtBudget: { bn: 'সরকারি বাজেট', en: 'Govt Budget' },
  aiEstimate: { bn: 'AI আনুমানিক ব্যয়', en: 'AI Estimated Cost' },
  budgetRisk: { bn: 'বাজেট ঝুঁকি', en: 'Budget Risk' },
  needed: { bn: 'দরকার', en: 'Needed' },
  neededButChange: { bn: 'দরকার কিন্তু পরিবর্তন চাই', en: 'Needed but changes required' },
  notNeeded: { bn: 'দরকার নেই', en: 'Not Needed' },
  yourReason: { bn: 'আপনার কারণ লিখুন', en: 'Write your reason' },
  submitOpinion: { bn: 'মতামত জমা দিন', en: 'Submit Opinion' },
  voteLockNotice: { bn: 'আপনি একবার মতামত দিলে তা পরিবর্তন করতে পারবেন না।', en: 'Once you submit your opinion, you cannot change it.' },
  weightedApproval: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Approval' },
  requiredThreshold: { bn: 'প্রয়োজন', en: 'Required' },
  status_open: { bn: 'মতামতের জন্য উন্মুক্ত', en: 'Open for Opinion' },
  status_closed: { bn: 'বন্ধ', en: 'Closed' },
  status_approved: { bn: 'অনুমোদিত', en: 'Approved' },
  status_rejected: { bn: 'প্রত্যাখ্যাত', en: 'Rejected' },
  impact_environment: { bn: 'পরিবেশ', en: 'Environment' },
  impact_displacement: { bn: 'স্থানচ্যুতি', en: 'Displacement' },
  impact_social: { bn: 'সামাজিক সুবিধা', en: 'Social Benefit' },
  impact_economic: { bn: 'অর্থনীতি', en: 'Economic' },

  // Govt Project Analysis
  materialBreakdown: { bn: 'উপকরণ খরচ বিশ্লেষণ', en: 'Material Breakdown' },
  qualityScenario: { bn: 'মান সিমুলেটর', en: 'Quality Simulator' },
  scenario_standard: { bn: 'স্ট্যান্ডার্ড', en: 'Standard' },
  scenario_high: { bn: 'উচ্চ মান', en: 'High Quality' },
  scenario_low: { bn: 'নিম্ন মান', en: 'Low Quality' },
  durability: { bn: 'স্থায়িত্ব', en: 'Durability' },
  timelineAdjust: { bn: 'সময়সীমা সমন্বয়', en: 'Timeline Adjustment' },
  months: { bn: 'মাস', en: 'Months' },
  govtProposed: { bn: 'সরকারি প্রস্তাবিত', en: 'Govt Proposed' },
  croreTaka: { bn: 'কোটি টাকা', en: 'Crore Taka' },
  costImpact: { bn: 'খরচ প্রভাব', en: 'Cost Impact' },

  // Tender Analysis
  tenderTitle: { bn: 'টেন্ডার ও ঠিকাদার বিশ্লেষণ', en: 'Tender & Contractor Analysis' },
  networkGraph: { bn: 'নেটওয়ার্ক গ্রাফ', en: 'Network Graph' },
  anomalies: { bn: 'শনাক্তকৃত অসঙ্গতি', en: 'Detected Anomalies' },
  riskSummary: { bn: 'ঝুঁকি সতর্কতা', en: 'Risk Alert' },
  syndicateDetected: { bn: 'সিন্ডিকেট শনাক্ত হয়েছে', en: 'Syndicate Detected' },
  investigationMode: { bn: 'অনুসন্ধান মোড', en: 'Investigation Mode' },
  contractorHistory: { bn: 'ঠিকাদারের ইতিহাস', en: 'Contractor History' },
  avgOverrun: { bn: 'গড় খরচ বৃদ্ধি', en: 'Avg. Cost Overrun' },
  delayRate: { bn: 'বিলম্বের হার', en: 'Delay Rate' },
  totalProjects: { bn: 'মোট প্রকল্প', en: 'Total Projects' },
  blacklistStatus: { bn: 'কালো তালিকাভুক্ত', en: 'Blacklist Status' },

  // Integrity Index
  integrityTitle: { bn: 'জাতীয় সততা সূচক', en: 'National Integrity Index' },
  nationalAvg: { bn: 'জাতীয় গড়', en: 'National Average' },
  topPerforming: { bn: 'সেরা জেলা', en: 'Top Performing' },
  criticalSector: { bn: 'ঝুঁকিপূর্ণ খাত', en: 'Critical Sector' },
  trendAnalysis: { bn: '৫ বছরের প্রবণতা', en: '5-Year Trend' },
  sectorBreakdown: { bn: 'খাতওয়ারী বিশ্লেষণ', en: 'Sector Breakdown' },
  riskFactor: { bn: 'প্রধান ঝুঁকি', en: 'Top Risk Factor' },
  solvedCases: { bn: 'মীমাংসিত কেস', en: 'Solved Cases' },
  districtInsights: { bn: 'জেলা ভিত্তিক তথ্য', en: 'District Insights' },
  rank: { bn: 'র‍্যাংক', en: 'Rank' },
  district: { bn: 'জেলা', en: 'District' },
  score: { bn: 'স্কোর', en: 'Score' },
  volunteerism: { bn: 'স্বেচ্ছাসেবী হার', en: 'Volunteerism' },
  resolutionTime: { bn: 'সমাধানের সময়', en: 'Resolution Time' },
  fairnessPerception: { bn: 'ন্যায্যতা ধারণা', en: 'Fairness Perception' },
  civicHealth: { bn: 'নাগরিক সুস্থতা', en: 'Civic Health' },
  communitySolidarity: { bn: 'কমিউনিটি সংহতি', en: 'Community Solidarity' },
  transparency: { bn: 'স্বচ্ছতা', en: 'Transparency' },
  publicTrust: { bn: 'জনগণের আস্থা', en: 'Public Trust' },
  lowestRanked: { bn: 'সর্বনিম্ন অবস্থান', en: 'Lowest Ranked' },
  highestRanked: { bn: 'শীর্ষ অবস্থান', en: 'Highest Ranked' },
  days: { bn: 'দিন', en: 'days' },

  // Hospital Monitor
  hospitalTitle: { bn: 'হাসপাতাল সেবা মনিটর', en: 'Hospital Service Monitor' },
  fairnessScore: { bn: 'সেবার মান', en: 'Fairness Score' },
  queueTime: { bn: 'গড় অপেক্ষার সময়', en: 'Avg Queue Time' },
  medicineStock: { bn: 'ঔষধ প্রাপ্যতা', en: 'Medicine Stock' },
  staffPresence: { bn: 'ডাক্তার উপস্থিতি', en: 'Doctor Presence' },
  bribeRisk: { bn: 'ঘুষের ঝুঁকি', en: 'Bribe Risk' },
  giveFeedback: { bn: 'গোপনে মতামত দিন', en: 'Give Anonymous Feedback' },
  minutes: { bn: 'মিনিট', en: 'min' },
  type_govt: { bn: 'সরকারি', en: 'Government' },
  type_private: { bn: 'বেসরকারি', en: 'Private' },
  stock_high: { bn: 'পর্যাপ্ত', en: 'High' },
  stock_medium: { bn: 'মাঝারি', en: 'Medium' },
  stock_low: { bn: 'স্বল্প', en: 'Low' },
  bribe_high: { bn: 'উচ্চ সতর্কতা', en: 'High Alert' },
  bribe_low: { bn: 'কম', en: 'Low' },
  bribe_medium: { bn: 'মাঝারি', en: 'Medium' },
  sortBy: { bn: 'সাজান', en: 'Sort By' },
  filterDistrict: { bn: 'জেলা', en: 'District' },
  filterType: { bn: 'ধরন', en: 'Type' },

  // Community Repair
  repairTitle: { bn: 'কমিউনিটি মেরামত', en: 'Community Repair' },
  iFixedIt: { bn: 'আমি ঠিক করেছি', en: 'I Fixed It' },
  urgency: { bn: 'জরুরী মাত্রা', en: 'Urgency' },
  verifyFix: { bn: 'যাচাই করুন', en: 'Verify Fix' },
  cat_road: { bn: 'রাস্তা ও পথ', en: 'Road & Path' },
  cat_drain: { bn: 'ড্রেনেজ', en: 'Drainage' },
  cat_light: { bn: 'ল্যাম্পপোস্ট', en: 'Street Light' },
  cat_trash: { bn: 'বর্জ্য অপসারণ', en: 'Trash Removal' },
  step_reported: { bn: 'রিপোর্ট করা হয়েছে', en: 'Reported' },
  step_attempt: { bn: 'মেরামত চলছে', en: 'Repair Attempt' },
  step_verify: { bn: 'যাচাই চলছে', en: 'Verifying' },
  step_closed: { bn: 'সম্পন্ন', en: 'Closed' },
  credits: { bn: 'ক্রেডিট', en: 'Credits' },
  autoResolve: { bn: 'পর্যাপ্ত যাচাই হলে এটি স্বয়ংক্রিয়ভাবে সম্পন্ন হিসেবে গণ্য হবে।', en: 'Will auto-resolve after sufficient verification.' },
  uploadProof: { bn: 'প্রমাণ আপলোড করুন', en: 'Upload Proof' },
  describeFix: { bn: 'কাজের বিবরণ দিন', en: 'Describe the fix' },
  submitFix: { bn: 'জমা দিন', en: 'Submit Fix' },
  rewardClaim: { bn: 'রিওয়ার্ড', en: 'Reward' },

  // Ethics & Oath
  ethicsReminder: { bn: 'নৈতিক স্মরণ', en: 'Ethics Reminder' },
  ethicsQuote: { bn: 'আল্লাহ তাআলা আমানত ঠিকভাবে আদায় করার নির্দেশ দিয়েছেন। (ভাবার্থ)', en: 'Indeed, Allah commands you to render trusts to whom they are due. (Quran 4:58)' },
  digitalOath: { bn: 'ডিজিটাল শপথ', en: 'Digital Oath' },
  oathPageTitle: { bn: 'নৈতিক ও নাগরিক শপথ', en: 'Ethical & Civic Oath' },
  rel_islam: { bn: 'ইসলাম', en: 'Islam' },
  rel_hindu: { bn: 'হিন্দু', en: 'Hindu' },
  rel_christian: { bn: 'খ্রিস্টান', en: 'Christian' },
  rel_buddhist: { bn: 'বৌদ্ধ', en: 'Buddhist' },
  rel_secular: { bn: 'সাধারণ', en: 'Secular' },
  
  text_islam: { bn: 'আমি আল্লাহ্‌র নামে শপথ করছি যে, আমি সর্বদা সত্য বলব, কারও হক নষ্ট করব না এবং এই প্ল্যাটফর্মটি শুধুমাত্র ন্যায় ও কল্যাণের জন্য ব্যবহার করব।', en: 'I swear by Allah that I will speak the truth, fulfill the rights of others, and use this platform only for justice and welfare.' },
  text_hindu: { bn: 'আমি ঈশ্বরের নামে শপথ করছি যে, আমি ধর্ম ও সত্যের পথে থাকব, মিথ্যা পরিহার করব এবং সমাজের মঙ্গলে কাজ করব।', en: 'I swear by God to follow the path of Dharma and Truth, avoid falsehood, and work for the welfare of society.' },
  text_christian: { bn: 'আমি ঈশ্বরের নামে প্রতিজ্ঞা করছি যে, আমি সততার সাথে আমার নাগরিক দায়িত্ব পালন করব এবং প্রতিবেশী ও সমাজের প্রতি বিশ্বস্ত থাকব।', en: 'I pledge before God to fulfill my civic duties with honesty and remain faithful to my neighbors and society.' },
  text_buddhist: { bn: 'আমি বুদ্ধের শিক্ষা স্মরণ করে প্রতিজ্ঞা করছি যে, আমি মিথ্যা ভাষণ থেকে বিরত থাকব এবং সকল প্রাণীর মঙ্গলে কাজ করব।', en: 'Remembering the teachings of Buddha, I pledge to refrain from false speech and work for the welfare of all beings.' },
  text_secular: { bn: 'আমি দেশের একজন দায়িত্বশীল নাগরিক হিসেবে শপথ করছি যে, আমি সংবিধানের প্রতি শ্রদ্ধাশীল থাকব এবং সততা ও নিষ্ঠার সাথে আমার নাগরিক দায়িত্ব পালন করব।', en: 'As a responsible citizen, I pledge to uphold the constitution and perform my civic duties with honesty and integrity.' },
  
  acceptOath: { bn: 'আমি এই শপথ গ্রহণ করছি', en: 'I accept this oath' },
  confirmOath: { bn: 'শপথ নিশ্চিত করুন', en: 'Confirm Oath' },
  oathAccepted: { bn: 'শপথ গ্রহণ সম্পন্ন হয়েছে', en: 'Oath Accepted' },
  acceptedOn: { bn: 'আপনি এই শপথ গ্রহণ করেছেন:', en: 'You accepted this oath on:' },
  backToHome: { bn: 'হোম এ ফিরে যান', en: 'Back to Home' },
};

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', labelBn: 'ড্যাশবোর্ড', labelEn: 'Dashboard', path: '/', icon: LayoutDashboard },
  { id: 'reports', labelBn: 'লাইভ রিপোর্ট', labelEn: 'Live Reports', path: '/reports', icon: Radio },
  { id: 'proposals', labelBn: 'প্রকল্প প্রস্তাবনা', labelEn: 'Proposals', path: '/proposals', icon: FileText },
  { id: 'govt', labelBn: 'সরকারি প্রকল্প', labelEn: 'Govt Projects', path: '/govt-projects', icon: Building2 },
  { id: 'tenders', labelBn: 'টেন্ডার বিশ্লেষণ', labelEn: 'Tender Analysis', path: '/tenders', icon: Briefcase },
  { id: 'integrity', labelBn: 'সততা সূচক', labelEn: 'Integrity Index', path: '/integrity', icon: Scale },
  { id: 'hospitals', labelBn: 'হাসপাতাল', labelEn: 'Hospitals', path: '/hospitals', icon: Stethoscope },
  { id: 'repair', labelBn: 'কমিউনিটি মেরামত', labelEn: 'Repair', path: '/repair', icon: Wrench },
  { id: 'oath', labelBn: 'ডিজিটাল শপথ', labelEn: 'Digital Oath', path: '/digital-oath', icon: ScrollText },
  { id: 'login', labelBn: 'প্রবেশ করুন', labelEn: 'Login', path: '/login', icon: LogIn },
  { id: 'signup', labelBn: 'নিবন্ধন', labelEn: 'Sign Up', path: '/signup', icon: UserPlus },
];