import { 
  LayoutDashboard, 
  Radio, 
  FileText, 
  Building2, 
  Scale, 
  Stethoscope, 
  Wrench,
  Search,
  Bell,
  Settings,
  LogOut,
  User,
  LogIn,
  UserPlus,
  Briefcase
} from 'lucide-react';
import { NavItem, TranslationDictionary } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  searchPlaceholder: { bn: 'অনুসন্ধান করুন...', en: 'Search...' },
  welcome: { bn: 'স্বাগতম', en: 'Welcome' },
  dashboard: { bn: 'ড্যাশবোর্ড', en: 'Dashboard' },
  liveReports: { bn: 'লাইভ রিপোর্ট', en: 'Live Reports' },
  projectProposals: { bn: 'প্রকল্প প্রস্তাবনা', en: 'Project Proposals' },
  govtProjects: { bn: 'সরকারি প্রকল্প', en: 'Govt Projects' },
  integrityIndex: { bn: 'সততা সূচক', en: 'Integrity Index' },
  hospitals: { bn: 'হাসপাতাল', en: 'Hospitals' },
  communityRepair: { bn: 'কমিউনিটি মেরামত', en: 'Community Repair' },
  tenderAnalysis: { bn: 'টেন্ডার বিশ্লেষণ', en: 'Tender Analysis' },
  footerDisclaimer: { bn: '© ২০২৪ নাগরিক সেবা। সর্বস্বত্ব সংরক্ষিত।', en: '© 2024 Nagorik Seba. All rights reserved.' },
  activeProjects: { bn: 'সক্রিয় প্রকল্প', en: 'Active Projects' },
  resolvedIssues: { bn: 'মীমাংসিত সমস্যা', en: 'Resolved Issues' },
  pendingReports: { bn: 'অপেক্ষমান রিপোর্ট', en: 'Pending Reports' },
  satisfactionRate: { bn: 'সন্তোষের হার', en: 'Satisfaction Rate' },
  citizenEngagement: { bn: 'নাগরিক অংশগ্রহণ', en: 'Citizen Engagement' },
  monthlyTrend: { bn: 'মাসিক প্রবণতা', en: 'Monthly Trend' },
  recentActivity: { bn: 'সাম্প্রতিক কার্যকলাপ', en: 'Recent Activity' },
  profile: { bn: 'প্রোফাইল', en: 'Profile' },
  settings: { bn: 'সেটিংস', en: 'Settings' },
  logout: { bn: 'লগ আউট', en: 'Log Out' },
  login: { bn: 'প্রবেশ করুন', en: 'Login' },
  signup: { bn: 'নিবন্ধন করুন', en: 'Sign Up' },
  mobileNumber: { bn: 'মোবাইল নম্বর', en: 'Mobile Number' },
  nidNumber: { bn: 'জাতীয় পরিচয়পত্র (NID)', en: 'NID Number' },
  password: { bn: 'পাসওয়ার্ড', en: 'Password' },
  verifyIdentity: { bn: 'পরিচয় যাচাই করুন', en: 'Verify Identity' },
  secureNote: { bn: 'আপনার পরিচয় এনক্রিপ্টেড থাকবে। পাবলিকভাবে কখনো দেখানো হবে না।', en: 'Your identity is encrypted and will never be shown publicly.' },
  otpTitle: { bn: 'যাচাইকরণ কোড', en: 'Verification Code' },
  otpSent: { bn: 'আপনার মোবাইলে ৬ সংখ্যার কোড পাঠানো হয়েছে', en: 'A 6-digit code has been sent to your mobile' },
  resend: { bn: 'পুনরায় পাঠান', en: 'Resend' },
  verify: { bn: 'যাচাই করুন', en: 'Verify' },
  oathTitle: { bn: 'নৈতিক শপথ', en: 'Ethical Oath' },
  oathText: { bn: 'আমি শপথ করছি যে, আমি সর্বদা সত্য বলব, কাউকে মিথ্যা অপবাদ দেব না এবং দেশের কল্যাণে এই প্ল্যাটফর্ম ব্যবহার করব।', en: 'I pledge to speak the truth, never slander anyone, and use this platform for the welfare of the country.' },
  iAgree: { bn: 'আমি সম্মত', en: 'I Agree' },
  continue: { bn: 'সামনে এগিয়ে যান', en: 'Continue' },
  congratulations: { bn: 'অভিনন্দন!', en: 'Congratulations!' },
  verifiedCitizen: { bn: 'যাচাইকৃত নাগরিক', en: 'Verified Citizen' },
  trustScore: { bn: 'ট্রাস্ট স্কোর', en: 'Trust Score' },
  publicProfile: { bn: 'আপনার পাবলিক প্রোফাইল', en: 'Your Public Profile' },
  generatedId: { bn: 'নাগরিক আইডি', en: 'Citizen ID' },
  backToLogin: { bn: 'লগিন এ ফিরে যান', en: 'Back to Login' },
  
  // Report Card Translations
  truthProbability: { bn: 'সত্যতার সম্ভাবনা', en: 'Truth Probability' },
  truthTooltip: { bn: 'এই স্কোর AI ও মানুষের যাচাই থেকে তৈরি।', en: 'Score generated from AI and human verification.' },
  weightedSupport: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Support' },
  support: { bn: 'সমর্থন করি', en: 'Support' },
  doubt: { bn: 'সন্দেহ আছে', en: 'Doubt' },
  aiBreakdown: { bn: 'AI বিশ্লেষণ', en: 'AI Analysis' },
  credibility: { bn: 'সমর্থনকারীদের বিশ্বাসযোগ্যতা', en: 'Supporter Credibility' },
  evidenceQuality: { bn: 'প্রমাণের মান', en: 'Evidence Quality' },
  mediaCheck: { bn: 'মিডিয়া যাচাই', en: 'Media Check' },
  historyMatch: { bn: 'আগের মিল থাকা কেস', en: 'Historical Match' },
  readMore: { bn: 'আরও পড়ুন', en: 'Read More' },
  showLess: { bn: 'কমিয়ে দেখুন', en: 'Show Less' },
  status_review: { bn: 'পর্যালোচনাধীন', en: 'Under Review' },
  status_verified: { bn: 'যাচাইকৃত', en: 'Verified' },
  status_disputed: { bn: 'বিতর্কিত', en: 'Disputed' },
  anonymous: { bn: 'বেনামী', en: 'Anonymous' },
  evidence: { bn: 'প্রমাণসমূহ', en: 'Evidence' },

  // Influence Monitoring Panel
  influencePanel: { bn: 'ইনফ্লুয়েন্স মনিটরিং প্যানেল', en: 'Influence Monitoring Panel' },
  risk_high: { bn: 'উচ্চ ঝুঁকি', en: 'High Risk' },
  risk_medium: { bn: 'মাঝারি ঝুঁকি', en: 'Medium Risk' },
  risk_low: { bn: 'কম ঝুঁকি', en: 'Low Risk' },
  coordinatedEffort: { bn: 'সম্ভাব্য সমন্বিত প্রচেষ্টা শনাক্ত', en: 'Potential Coordinated Effort Detected' },
  voteSpike: { bn: 'ভোট বৃদ্ধি', en: 'Vote Spike' },
  abnormalSpike: { bn: 'এই সময়ে অস্বাভাবিক ভোট বৃদ্ধি হয়েছে', en: 'Abnormal vote spike detected at this time' },
  geoCluster: { bn: 'ভৌগোলিক ক্লাস্টার বিশ্লেষণ', en: 'Geographic Cluster Analysis' },
  aiExplanation: { bn: 'একই সময়ে নতুন অ্যাকাউন্ট থেকে বহু সমর্থন আসায় কিছু ভোটের ওজন কমানো হয়েছে।', en: 'Some vote weights were reduced due to multiple supports from new accounts at the same time.' },
  transparencyNote: { bn: 'এই বিশ্লেষণ স্বয়ংক্রিয় AI দ্বারা করা হয়েছে এবং মানব মডারেটর পর্যালোচনা করতে পারে।', en: 'This analysis was done by automated AI and may be reviewed by human moderators.' },

  // Project Proposals
  aiSimpleExplain: { bn: 'AI সহজ ভাষায় ব্যাখ্যা', en: 'AI Simplified Explanation' },
  govtBudget: { bn: 'সরকারি বাজেট', en: 'Govt Budget' },
  aiEstimate: { bn: 'AI আনুমানিক ব্যয়', en: 'AI Estimated Cost' },
  budgetRisk: { bn: 'বাজেট ঝুঁকি', en: 'Budget Risk' },
  needed: { bn: 'দরকার', en: 'Needed' },
  neededButChange: { bn: 'দরকার কিন্তু পরিবর্তন চাই', en: 'Needed but changes required' },
  notNeeded: { bn: 'দরকার নেই', en: 'Not Needed' },
  yourReason: { bn: 'আপনার কারণ লিখুন', en: 'Write your reason' },
  submitOpinion: { bn: 'মতামত জমা দিন', en: 'Submit Opinion' },
  voteLockNotice: { bn: 'আপনি একবার মতামত দিলে তা পরিবর্তন করতে পারবেন না।', en: 'Once you submit your opinion, you cannot change it.' },
  weightedApproval: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Approval' },
  requiredThreshold: { bn: 'প্রয়োজন', en: 'Required' },
  status_open: { bn: 'মতামতের জন্য উন্মুক্ত', en: 'Open for Opinion' },
  status_closed: { bn: 'বন্ধ', en: 'Closed' },
  status_approved: { bn: 'অনুমোদিত', en: 'Approved' },
  status_rejected: { bn: 'প্রত্যাখ্যাত', en: 'Rejected' },
  impact_environment: { bn: 'পরিবেশ', en: 'Environment' },
  impact_displacement: { bn: 'স্থানচ্যুতি', en: 'Displacement' },
  impact_social: { bn: 'সামাজিক সুবিধা', en: 'Social Benefit' },
  impact_economic: { bn: 'অর্থনীতি', en: 'Economic' },

  // Govt Project Analysis
  materialBreakdown: { bn: 'উপকরণ খরচ বিশ্লেষণ', en: 'Material Breakdown' },
  qualityScenario: { bn: 'মান সিমুলেটর', en: 'Quality Simulator' },
  scenario_standard: { bn: 'স্ট্যান্ডার্ড', en: 'Standard' },
  scenario_high: { bn: 'উচ্চ মান', en: 'High Quality' },
  scenario_low: { bn: 'নিম্ন মান', en: 'Low Quality' },
  durability: { bn: 'স্থায়িত্ব', en: 'Durability' },
  timelineAdjust: { bn: 'সময়সীমা সমন্বয়', en: 'Timeline Adjustment' },
  months: { bn: 'মাস', en: 'Months' },
  govtProposed: { bn: 'সরকারি প্রস্তাবিত', en: 'Govt Proposed' },
  croreTaka: { bn: 'কোটি টাকা', en: 'Crore Taka' },
  costImpact: { bn: 'খরচ প্রভাব', en: 'Cost Impact' },

  // Tender Analysis
  tenderTitle: { bn: 'টেন্ডার ও ঠিকাদার বিশ্লেষণ', en: 'Tender & Contractor Analysis' },
  networkGraph: { bn: 'নেটওয়ার্ক গ্রাফ', en: 'Network Graph' },
  anomalies: { bn: 'শনাক্তকৃত অসঙ্গতি', en: 'Detected Anomalies' },
  riskSummary: { bn: 'ঝুঁকি সতর্কতা', en: 'Risk Alert' },
  syndicateDetected: { bn: 'সিন্ডিকেট শনাক্ত হয়েছে', en: 'Syndicate Detected' },
  investigationMode: { bn: 'অনুসন্ধান মোড', en: 'Investigation Mode' },
  contractorHistory: { bn: 'ঠিকাদারের ইতিহাস', en: 'Contractor History' },
  avgOverrun: { bn: 'গড় খরচ বৃদ্ধি', en: 'Avg. Cost Overrun' },
  delayRate: { bn: 'বিলম্বের হার', en: 'Delay Rate' },
  totalProjects: { bn: 'মোট প্রকল্প', en: 'Total Projects' },
  blacklistStatus: { bn: 'কালো তালিকাভুক্ত', en: 'Blacklist Status' },

  // Integrity Index
  integrityTitle: { bn: 'জাতীয় সততা সূচক', en: 'National Integrity Index' },
  nationalAvg: { bn: 'জাতীয় গড়', en: 'National Average' },
  topPerforming: { bn: 'সেরা জেলা', en: 'Top Performing' },
  criticalSector: { bn: 'ঝুঁকিপূর্ণ খাত', en: 'Critical Sector' },
  trendAnalysis: { bn: '৫ বছরের প্রবণতা', en: '5-Year Trend' },
  sectorBreakdown: { bn: 'খাতওয়ারী বিশ্লেষণ', en: 'Sector Breakdown' },
  riskFactor: { bn: 'প্রধান ঝুঁকি', en: 'Top Risk Factor' },
  solvedCases: { bn: 'মীমাংসিত কেস', en: 'Solved Cases' },
  districtInsights: { bn: 'জেলা ভিত্তিক তথ্য', en: 'District Insights' },

  // Hospital Monitor
  hospitalTitle: { bn: 'হাসপাতাল সেবা মনিটর', en: 'Hospital Service Monitor' },
  fairnessScore: { bn: 'সেবার মান', en: 'Fairness Score' },
  queueTime: { bn: 'গড় অপেক্ষার সময়', en: 'Avg Queue Time' },
  medicineStock: { bn: 'ঔষধ প্রাপ্যতা', en: 'Medicine Stock' },
  staffPresence: { bn: 'ডাক্তার উপস্থিতি', en: 'Doctor Presence' },
  bribeRisk: { bn: 'ঘুষের ঝুঁকি', en: 'Bribe Risk' },
  giveFeedback: { bn: 'গোপনে মতামত দিন', en: 'Give Anonymous Feedback' },
  minutes: { bn: 'মিনিট', en: 'min' },
  type_govt: { bn: 'সরকারি', en: 'Government' },
  type_private: { bn: 'বেসরকারি', en: 'Private' },
  stock_high: { bn: 'পর্যাপ্ত', en: 'High' },
  stock_medium: { bn: 'মাঝারি', en: 'Medium' },
  stock_low: { bn: 'স্বল্প', en: 'Low' },
  bribe_high: { bn: 'উচ্চ সতর্কতা', en: 'High Alert' },
  bribe_low: { bn: 'কম', en: 'Low' },
  bribe_medium: { bn: 'মাঝারি', en: 'Medium' },
  sortBy: { bn: 'সাজান', en: 'Sort By' },
  filterDistrict: { bn: 'জেলা', en: 'District' },
  filterType: { bn: 'ধরন', en: 'Type' },
};

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', labelBn: 'ড্যাশবোর্ড', labelEn: 'Dashboard', path: '/', icon: LayoutDashboard },
  { id: 'reports', labelBn: 'লাইভ রিপোর্ট', labelEn: 'Live Reports', path: '/reports', icon: Radio },
  { id: 'proposals', labelBn: 'প্রকল্প প্রস্তাবনা', labelEn: 'Proposals', path: '/proposals', icon: FileText },
  { id: 'govt', labelBn: 'সরকারি প্রকল্প', labelEn: 'Govt Projects', path: '/govt-projects', icon: Building2 },
  { id: 'tenders', labelBn: 'টেন্ডার বিশ্লেষণ', labelEn: 'Tender Analysis', path: '/tenders', icon: Briefcase },
  { id: 'integrity', labelBn: 'সততা সূচক', labelEn: 'Integrity Index', path: '/integrity', icon: Scale },
  { id: 'hospitals', labelBn: 'হাসপাতাল', labelEn: 'Hospitals', path: '/hospitals', icon: Stethoscope },
  { id: 'repair', labelBn: 'কমিউনিটি মেরামত', labelEn: 'Repair', path: '/repair', icon: Wrench },
  { id: 'login', labelBn: 'প্রবেশ করুন', labelEn: 'Login', path: '/login', icon: LogIn },
  { id: 'signup', labelBn: 'নিবন্ধন', labelEn: 'Sign Up', path: '/signup', icon: UserPlus },
];