
import { 
  LayoutDashboard, 
  Building2, 
  Scale, 
  Stethoscope, 
  Wrench,
  Bell,
  Settings,
  LogOut,
  User,
  ScrollText,
  ShieldAlert,
  FileClock,
  Gavel,
  Unlock,
  Archive,
  AlertOctagon,
  Bot,
  FileCheck,
  Map,
  Siren,
  Home,
  BarChart2,
  Landmark,
  FileQuestion,
  // Fix: Added missing imports to resolve errors on lines 367, 383, and 384
  Briefcase,
  FileText
} from 'lucide-react';
import { NavItem, TranslationDictionary } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  searchPlaceholder: { bn: 'অনুসন্ধান করুন...', en: 'Search...' },
  welcome: { bn: 'স্বাগতম', en: 'Welcome' },
  dashboard: { bn: 'ফিড ও রিপোর্ট', en: 'Feed & Reports' },
  analytics: { bn: 'ড্যাশবোর্ড', en: 'Dashboard' },
  liveReports: { bn: 'লাইভ রিপোর্ট', en: 'Live Reports' },
  projectProposals: { bn: 'প্রকল্প প্রস্তাবনা', en: 'Project Proposals' },
  govtProjects: { bn: 'উন্নয়ন প্রকল্প ও প্রস্তাবনা', en: 'Projects & Proposals' },
  integrityIndex: { bn: 'সততা সূচক', en: 'Integrity Index' },
  hospitals: { bn: 'হাসপাতাল', en: 'Hospitals' },
  communityRepair: { bn: 'কমিউনিটি মেরামত', en: 'Community Repair' },
  tenderAnalysis: { bn: 'টেন্ডার বিশ্লেষণ', en: 'Tender Analysis' },
  moderationQueue: { bn: 'মডারেশন কিউ', en: 'Moderation Queue' },
  auditLogs: { bn: 'অডিট লগ', en: 'Audit Logs' },
  courtOrders: { bn: 'আদালতের আদেশ', en: 'Court Orders' },
  identityUnlock: { bn: 'পরিচয় আনলক', en: 'Identity Unlock' },
  footerDisclaimer: { bn: '© ২০২৪ নাগরিক সেবা। সর্বস্বত্ব সংরক্ষিত।', en: '© 2024 Nagorik Seba. All rights reserved.' },
  activeProjects: { bn: 'সক্রিয় প্রকল্প', en: 'Active Projects' },
  resolvedIssues: { bn: 'মীমাংসিত সমস্যা', en: 'Resolved Issues' },
  pendingReports: { bn: 'অপেক্ষমান রিপোর্ট', en: 'Pending Reports' },
  citizenEngagement: { bn: 'নাগরিক অংশগ্রহণ', en: 'Citizen Engagement' },
  monthlyTrend: { bn: 'মাসিক প্রবণতা', en: 'Monthly Trend' },
  profile: { bn: 'প্রোফাইল', en: 'Profile' },
  settings: { bn: 'সেটিংস', en: 'Settings' },
  logout: { bn: 'লগ আউট', en: 'Log Out' },
  login: { bn: 'প্রবেশ করুন', en: 'Login' },
  signup: { bn: 'নিবন্ধন করুন', en: 'Sign Up' },
  mobileNumber: { bn: 'মোবাইল নম্বর', en: 'Mobile Number' },
  nidNumber: { bn: 'জাতীয় পরিচয়পত্র (NID)', en: 'NID Number' },
  password: { bn: 'পাসওয়ার্ড', en: 'Password' },
  verifyIdentity: { bn: 'পরিচয় যাচাই করুন', en: 'Verify Identity' },
  secureNote: { bn: 'আপনার পরিচয় এনক্রিপ্টেড থাকবে। পাবলিকভাবে কখনো দেখানো হবে না।', en: 'Your identity is encrypted and will never be shown publicly.' },
  otpTitle: { bn: 'যাচাইকরণ কোড', en: 'Verification Code' },
  otpSent: { bn: 'আপনার মোবাইলে ৬ সংখ্যার কোড পাঠানো হয়েছে', en: 'A 6-digit code has been sent to your mobile' },
  resend: { bn: 'পুনরায় পাঠান', en: 'Resend' },
  verify: { bn: 'যাচাই করুন', en: 'Verify' },
  oathTitle: { bn: 'নৈতিক শপথ', en: 'Ethical Oath' },
  oathText: { bn: 'আমি শপথ করছি যে, আমি সর্বদা সত্য বলব, কাউকে মিথ্যা অপবাদ দেব না এবং দেশের কল্যাণে এই প্ল্যাটফর্ম ব্যবহার করব।', en: 'I pledge to speak the truth, never slander anyone, and use this platform for the welfare of the country.' },
  iAgree: { bn: 'আমি সম্মত', en: 'I Agree' },
  continue: { bn: 'সামনে এগিয়ে যান', en: 'Continue' },
  congratulations: { bn: 'অভিনন্দন!', en: 'Congratulations!' },
  verifiedCitizen: { bn: 'যাচাইকৃত নাগরিক', en: 'Verified Citizen' },
  trustScore: { bn: 'ট্রাস্ট স্কোর', en: 'Trust Score' },
  publicProfile: { bn: 'আপনার পাবলিক প্রোফাইল', en: 'Your Public Profile' },
  generatedId: { bn: 'নাগরিক আইডি', en: 'Citizen ID' },
  backToLogin: { bn: 'লগিন এ ফিরে যান', en: 'Back to Login' },
  follow: { bn: 'ফলো করুন', en: 'Follow' },
  following: { bn: 'ফলো করছেন', en: 'Following' },
  notifications: { bn: 'নোটিফিকেশন', en: 'Notifications' },
  markAllRead: { bn: 'সব পঠিত হিসেবে চিহ্নিত করুন', en: 'Mark all as read' },
  noNotifications: { bn: 'কোনো নতুন নোটিফিকেশন নেই', en: 'No new notifications' },
  viewAll: { bn: 'সব দেখুন', en: 'View All' },
  notificationCenter: { bn: 'নোটিফিকেশন সেন্টার', en: 'Notification Center' },
  ministryTransparency: { bn: 'মন্ত্রণালয় স্বচ্ছতা সূচক', en: 'Ministry Transparency Index' },
  ministry: { bn: 'মন্ত্রণালয়', en: 'Ministry' },
  overallScore: { bn: 'সামগ্রিক স্কোর', en: 'Overall Score' },
  complaintsCount: { bn: 'অভিযোগ সংখ্যা', en: 'Complaints' },
  avgDelay: { bn: 'গড় বিলম্ব', en: 'Avg Delay' },
  budgetOverrun: { bn: 'বাজেট বিচ্যুতি', en: 'Budget Overrun' },
  citizenTrust: { bn: 'নাগরিক আস্থা', en: 'Citizen Trust' },
  rank: { bn: 'র‍্যাংক', en: 'Rank' },
  compareMinistries: { bn: 'মন্ত্রণালয় তুলনা', en: 'Compare Ministries' },
  selectMinistry: { bn: 'মন্ত্রণালয় নির্বাচন করুন', en: 'Select Ministry' },
  vs: { bn: 'বনাম', en: 'vs' },
  rtiRequest: { bn: 'তথ্য অনুরোধ (RTI)', en: 'RTI Request' },
  rtiDescription: { bn: 'তথ্য অধিকার আইনে সরকারি দপ্তর থেকে তথ্য প্রাপ্তির আবেদন করুন।', en: 'File a request for information from govt departments under the RTI Act.' },
  newRequest: { bn: 'নতুন আবেদন', en: 'New Request' },
  publicLibrary: { bn: 'পাবলিক লাইব্রেরি', en: 'Public Library' },
  myRequests: { bn: 'আমার আবেদন', en: 'My Requests' },
  subject: { bn: 'বিষয়', en: 'Subject' },
  department: { bn: 'দপ্তর / মন্ত্রণালয়', en: 'Department' },
  details: { bn: 'বিস্তারিত বিবরণ', en: 'Details' },
  category: { bn: 'বিভাগ', en: 'Category' },
  privacySetting: { bn: 'গোপনীয়তা সেটিিংস', en: 'Privacy Settings' },
  public: { bn: 'পাবলিক (সবাই দেখবে)', en: 'Public' },
  private: { bn: 'প্রাইভেট (গোপন)', en: 'Private' },
  submitRTI: { bn: 'আবেদন জমা দিন', en: 'Submit Request' },
  daysRemaining: { bn: 'সময় বাকি', en: 'Days Remaining' },
  admin_rti: { bn: 'RTI ব্যবস্থাপনা', en: 'RTI Management' },
  admin_dashboard: { bn: 'অ্যাডমিন ড্যাশবোর্ড', en: 'Admin Dashboard' },
  admin_moderation: { bn: 'মডারেশন কিউ', en: 'Moderation Queue' },
  admin_reports: { bn: 'রিপোর্ট পর্যালোচনা', en: 'Report Review' },
  admin_evidence: { bn: 'প্রমাণ ভল্ট', en: 'Evidence Vault' },
  admin_anomalies: { bn: 'ভোট অসঙ্গতি', en: 'Vote Anomalies' },
  admin_bots: { bn: 'বট কার্যকলাপ', en: 'Bot Activity' },
  admin_approvals: { bn: 'প্রকল্প অনুমোদন', en: 'Project Approvals' },
  admin_tenders: { bn: 'টেন্ডার তদারকি', en: 'Tender Oversight' },
  admin_districts: { bn: 'জেলা নিয়ন্ত্রণ', en: 'District Controls' },
  admin_audit: { bn: 'অডিট লগ', en: 'Audit Logs' },
  admin_court: { bn: 'আদালতের আদেশ', en: 'Court Orders' },
  admin_identity: { bn: 'পরিচয় অনুরোধ', en: 'Identity Requests' },
  admin_crisis: { bn: 'জরুরি নিয়ন্ত্রণ', en: 'Crisis Control' },
  truthProbability: { bn: 'সত্যতার সম্ভাবনা', en: 'Truth Probability' },
  truthTooltip: { bn: 'এই স্কোর AI ও মানুষের যাচাই থেকে তৈরি।', en: 'Score generated from AI and human verification.' },
  weightedSupport: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Support' },
  support: { bn: 'সমর্থন করি', en: 'Support' },
  doubt: { bn: 'সন্দেহ আছে', en: 'Doubt' },
  status_review: { bn: 'পর্যালোচনাধীন', en: 'Under Review' },
  status_verified: { bn: 'যাচাইকৃত', en: 'Verified' },
  status_disputed: { bn: 'বিতর্কিত', en: 'Disputed' },
  anonymous: { bn: 'বেনামী', en: 'Anonymous' },
  tab_discussion: { bn: 'আলোচনা', en: 'Discussion' },
  tab_evidence: { bn: 'অতিরিক্ত প্রমাণ', en: 'Add Evidence' },
  tab_timeline: { bn: 'টাইমলাইন', en: 'Timeline' },
  sort_trusted: { bn: 'বিশ্বস্ত', en: 'Most Trusted' },
  sort_recent: { bn: 'সাম্প্রতিক', en: 'Recent' },
  local_resident: { bn: 'স্থানীয়', en: 'Local' },
  agree: { bn: 'সহমত', en: 'Agree' },
  disagree: { bn: 'অসম্মত', en: 'Disagree' },
  badge_engineer: { bn: 'প্রকৌশলী', en: 'Engineer' },
  badge_doctor: { bn: 'ডাক্তার', en: 'Doctor' },
  badge_lawyer: { bn: 'আইনজীবী', en: 'Lawyer' },
  badge_accountant: { bn: 'অ্যাকাউন্ট্যান্ট', en: 'Accountant' },
  verified_area: { bn: 'এই এলাকায় যাচাইকৃত', en: 'Verified in this area' },
  verification_tooltip: { bn: 'এই তথ্য ভেরিফিকেশনের মাধ্যমে নিশ্চিত করা হয়েছে', en: 'This information has been confirmed via verification' },
  report_abuse: { bn: 'অভিযোগ করুন', en: 'Report Abuse' },
  flag_reason: { bn: 'অভিযোগের কারণ', en: 'Reason for reporting' },
  reason_misinfo: { bn: 'মিথ্যা তথ্য', en: 'Misinformation' },
  reason_defamation: { bn: 'মানহানিকর', en: 'Defamation' },
  reason_hate: { bn: 'ঘৃণামূলক বক্তব্য', en: 'Hate Speech' },
  reason_fake: { bn: 'ভুয়া প্রমাণ', en: 'Fake Evidence' },
  reason_other: { bn: 'অন্য', en: 'Other' },
  submit_report: { bn: 'জমা দিন', en: 'Submit Report' },
  report_submitted: { bn: 'অভিযোগ জমা দেওয়া হয়েছে', en: 'Report Submitted' },
  moderation_status: { bn: 'মডারেশন স্ট্যাটাস', en: 'Moderation Status' },
  status_pending: { bn: 'পর্যালোচনা চলছে', en: 'Pending Review' },
  status_removed: { bn: 'অপসারিত', en: 'Removed' },
  status_restored: { bn: 'পুনরুদ্ধারকৃত', en: 'Restored' },
  appeal_status: { bn: 'আপিল স্ট্যাটাস', en: 'Appeal Status' },
  transparency_log: { bn: 'স্বচ্ছতা লগ', en: 'Transparency Log' },
  log_ai_flag: { bn: 'AI দ্বারা চিহ্নিত', en: 'Flagged by AI' },
  log_user_report: { bn: 'ব্যবহারকারী রিপোর্ট', en: 'User Report' },
  log_mod_action: { bn: 'মডারেটর অ্যাকশন', en: 'Moderator Action' },
  log_legal: { bn: 'আইনি নোটিশ', en: 'Legal Notice' },
  compliance_banner: { bn: 'এই তথ্য শুধুমাত্র আইনগত আ আদেশ প্রকাশযোগ্য।', en: 'This information is only revealable via legal order.' },
  audit_actor: { bn: 'অ্যাক্টর', en: 'Actor' },
  audit_action: { bn: 'অ্যাকশন', en: 'Action' },
  audit_hash: { bn: 'ক্রিপ্টোগ্রাফিক হ্যাশ', en: 'Cryptographic Hash' },
  court_case_no: { bn: 'মামলা নং', en: 'Case Number' },
  court_name: { bn: 'আদালতের নাম', en: 'Court Name' },
  upload_order: { bn: 'আদেশ আপলোড করুন', en: 'Upload Order' },
  unlock_request: { bn: 'আনলক অনুরোধ', en: 'Unlock Request' },
  dual_approval: { bn: 'ডুয়াল অনুমোদন অপেক্ষমান', en: 'Dual Approval Pending' },
  legal_review: { bn: 'আইনি পর্যালোচনা', en: 'Legal Review' },
  identity_revealed: { bn: 'পরিচয় প্রকাশ করা হয়েছে', en: 'Identity Revealed' },
  dragDrop: { bn: 'ছবি বা ভিডিও এখানে ড্রপ করুন', en: 'Drop photos or videos here' },
  addDesc: { bn: 'বিবরণ যোগ করুন...', en: 'Add a description...' },
  submitEvidence: { bn: 'প্রমাণ জমা দিন', en: 'Submit Evidence' },
  event_created: { bn: 'রিপোর্ট তৈরি হয়েছে', en: 'Report Created' },
  event_ai_check: { bn: 'AI যাচাইকরণ সম্পন্ন', en: 'AI Verification Complete' },
  event_evidence: { bn: 'নতুন প্রমাণ যুক্ত হয়েছে', en: 'New Evidence Added' },
  event_review: { bn: 'মডারেটর রিভিউ', en: 'Moderator Review' },
  influencePanel: { bn: 'ইনফ্লুয়েন্স মনিটরিং প্যানেল', en: 'Influence Monitoring Panel' },
  risk_high: { bn: 'উচ্চ ঝুঁকি', en: 'High Risk' },
  risk_medium: { bn: 'মাঝারি ঝুঁকি', en: 'Medium Risk' },
  risk_low: { bn: 'কম ঝুঁকি', en: 'Low Risk' },
  coordinatedEffort: { bn: 'সম্ভাব্য সমন্বিত প্রচেষ্টা শনাক্ত', en: 'Potential Coordinated Effort Detected' },
  voteSpike: { bn: 'ভোট বৃদ্ধি', en: 'Vote Spike' },
  abnormalSpike: { bn: 'এই সময়ে অস্বাভাবিক ভোট বৃদ্ধি হয়েছে', en: 'Abnormal vote spike detected at this time' },
  geoCluster: { bn: 'ভৌগোলিক ক্লাস্টার বিশ্লেষণ', en: 'Geographic Cluster Analysis' },
  aiExplanation: { bn: 'একই সময়ে নতুন অ্যাকাউন্ট থেকে বহু সমর্থন আসায় কিছু ভোটের ওজন কমানো হয়েছে।', en: 'Some vote weights were reduced due to multiple supports from new accounts at the same time.' },
  transparencyNote: { bn: 'এই বিশ্লেষণ স্বয়ংক্রিয় AI দ্বারা করা হয়েছে এবং মানব মডারেটর পর্যালোচনা করতে পারে।', en: 'This analysis was done by automated AI and may be reviewed by human moderators.' },
  aiSimpleExplain: { bn: 'AI সহজ ভাষায় ব্যাখ্যা', en: 'AI Simplified Explanation' },
  govtBudget: { bn: 'সরকারি বাজেট', en: 'Govt Budget' },
  aiEstimate: { bn: 'AI আনুমানিক ব্যয়', en: 'AI Estimated Cost' },
  budgetRisk: { bn: 'বাজেট ঝুঁকি', en: 'Budget Risk' },
  needed: { bn: 'দরকার', en: 'Needed' },
  neededButChange: { bn: 'দরকার কিন্তু পরিবর্তন চাই', en: 'Needed but changes required' },
  notNeeded: { bn: 'দরকার নেই', en: 'Not Needed' },
  yourReason: { bn: 'আপনার কারণ লিখুন', en: 'Write your reason' },
  submitOpinion: { bn: 'মতামত জমা দিন', en: 'Submit Opinion' },
  voteLockNotice: { bn: 'আপনি একবার মতামত দিলে তা পরিবর্তন করতে পারবেন না।', en: 'Once you submit your opinion, you cannot change it.' },
  weightedApproval: { bn: 'ওজনযুক্ত সমর্থন', en: 'Weighted Approval' },
  status_open: { bn: 'মতামতের জন্য উন্মুক্ত', en: 'Open for Opinion' },
  status_closed: { bn: 'বন্ধ', en: 'Closed' },
  status_approved: { bn: 'অনুমোদিত', en: 'Approved' },
  status_rejected: { bn: 'প্রত্যাখ্যাত', en: 'Rejected' },
  impact_environment: { bn: 'পরিবেশ', en: 'Environment' },
  impact_displacement: { bn: 'স্থানচ্যুতি', en: 'Displacement' },
  impact_social: { bn: 'সামাজিক সুবিধা', en: 'Social Benefit' },
  impact_economic: { bn: 'অর্থনীতি', en: 'Economic' },
  materialBreakdown: { bn: 'উপকরণ খরচ বিশ্লেষণ', en: 'Material Breakdown' },
  qualityScenario: { bn: 'মান সিমুলেটর', en: 'Quality Simulator' },
  scenario_standard: { bn: 'স্ট্যান্ডার্ড', en: 'Standard' },
  scenario_high: { bn: 'উচ্চ মান', en: 'High Quality' },
  scenario_low: { bn: 'নিম্ন মান', en: 'Low Quality' },
  durability: { bn: 'স্থায়িত্ব', en: 'Durability' },
  timelineAdjust: { bn: 'সময়সীমা সমন্বয়', en: 'Timeline Adjustment' },
  months: { bn: 'মাস', en: 'Months' },
  govtProposed: { bn: 'সরকারি প্রস্তাবিত', en: 'Govt Proposed' },
  croreTaka: { bn: 'কোটি টাকা', en: 'Crore Taka' },
  costImpact: { bn: 'খরচ প্রভাব', en: 'Cost Impact' },
  tenderTitle: { bn: 'টেন্ডার ও ঠিকাদার বিশ্লেষণ', en: 'Tender & Contractor Analysis' },
  networkGraph: { bn: 'নেটওয়ার্ক গ্রাফ', en: 'Network Graph' },
  anomalies: { bn: 'শনাক্তকৃত অসঙ্গতি', en: 'Detected Anomalies' },
  riskSummary: { bn: 'ঝুঁকি সতর্কতা', en: 'Risk Alert' },
  syndicateDetected: { bn: 'সিন্ডিকেট শনাক্ত হয়েছে', en: 'Syndicate Detected' },
  investigationMode: { bn: 'অনুসন্ধান মোড', en: 'Investigation Mode' },
  contractorHistory: { bn: 'ঠিকাদারের ইতিহাস', en: 'Contractor History' },
  avgOverrun: { bn: 'গড় খরচ বৃদ্ধি', en: 'Avg. Cost Overrun' },
  delayRate: { bn: 'বিলম্বের হার', en: 'Delay Rate' },
  totalProjects: { bn: 'মোট প্রকল্প', en: 'Total Projects' },
  blacklistStatus: { bn: 'কালো তালিকাভুক্ত', en: 'Blacklist Status' },
  integrityTitle: { bn: 'জাতীয় সততা সূচক', en: 'National Integrity Index' },
  nationalAvg: { bn: 'জাতীয় গড়', en: 'National Average' },
  topPerforming: { bn: 'সেরা জেলা', en: 'Top Performing' },
  criticalSector: { bn: 'ঝুঁকিপূর্ণ খাত', en: 'Critical Sector' },
  trendAnalysis: { bn: '৫ বছরের প্রবণতা', en: '5-Year Trend' },
  sectorBreakdown: { bn: 'খাতওয়ারী বিশ্লেষণ', en: 'Sector Breakdown' },
  riskFactor: { bn: 'প্রধান ঝুঁকি', en: 'Top Risk Factor' },
  solvedCases: { bn: 'মীমাংসিত কেস', en: 'Solved Cases' },
  districtInsights: { bn: 'জেলা ভিত্তিক তথ্য', en: 'District Insights' },
  district: { bn: 'জেলা', en: 'District' },
  score: { bn: 'স্কোর', en: 'Score' },
  volunteerism: { bn: 'স্বেচ্ছাসেবী হার', en: 'Volunteerism' },
  resolutionTime: { bn: 'সমাধানের সময়', en: 'Resolution Time' },
  fairnessPerception: { bn: 'ন্যায্যতা ধারণা', en: 'Fairness Perception' },
  civicHealth: { bn: 'নাগরিক সুস্থতা', en: 'Civic Health' },
  communitySolidarity: { bn: 'কমিউনিটি সংহতি', en: 'Community Solidarity' },
  transparency: { bn: 'স্বচ্ছতা', en: 'Transparency' },
  publicTrust: { bn: 'জনগণের আস্থা', en: 'Public Trust' },
  lowestRanked: { bn: 'সর্বনিম্ন অবস্থান', en: 'Lowest Ranked' },
  highestRanked: { bn: 'শীর্ষ অবস্থান', en: 'Highest Ranked' },
  days: { bn: 'দিন', en: 'days' },
  hospitalTitle: { bn: 'হাসপাতাল সেবা মনিটর', en: 'Hospital Service Monitor' },
  fairnessScore: { bn: 'সেবার মান', en: 'Fairness Score' },
  queueTime: { bn: 'গড় অপেক্ষার সময়', en: 'Avg Queue Time' },
  medicineStock: { bn: 'ঔষধ প্রাপ্যতা', en: 'Medicine Stock' },
  staffPresence: { bn: 'ডাক্তার উপস্থিতি', en: 'Doctor Presence' },
  bribeRisk: { bn: 'ঘুষের ঝুঁকি', en: 'Bribe Risk' },
  giveFeedback: { bn: 'গোপনে মতামত দিন', en: 'Give Anonymous Feedback' },
  minutes: { bn: 'মিনিট', en: 'min' },
  type_govt: { bn: 'সরকারি', en: 'Government' },
  type_private: { bn: 'বেসরকারি', en: 'Private' },
  stock_high: { bn: 'পর্যাপ্ত', en: 'High' },
  stock_medium: { bn: 'মাঝারি', en: 'Medium' },
  stock_low: { bn: 'স্বল্প', en: 'Low' },
  bribe_high: { bn: 'উচ্চ সতর্কতা', en: 'High Alert' },
  bribe_low: { bn: 'কম', en: 'Low' },
  bribe_medium: { bn: 'মাঝারি', en: 'Medium' },
  sortBy: { bn: 'সাজান', en: 'Sort By' },
  filterDistrict: { bn: 'জেলা', en: 'District' },
  filterType: { bn: 'ধরন', en: 'Type' },
  repairTitle: { bn: 'কমিউনিটি মেরামত', en: 'Community Repair' },
  iFixedIt: { bn: 'আমি ঠিক করেছি', en: 'I Fixed It' },
  urgency: { bn: 'জরুরী মাত্রা', en: 'Urgency' },
  verifyFix: { bn: 'যাচাই করুন', en: 'Verify Fix' },
  cat_road: { bn: 'রাস্তা ও পথ', en: 'Road & Path' },
  cat_drain: { bn: 'ড্রেনেজ', en: 'Drainage' },
  cat_light: { bn: 'ল্যাম্পপোস্ট', en: 'Street Light' },
  cat_trash: { bn: 'বর্জ্য অপসারণ', en: 'Trash Removal' },
  step_reported: { bn: 'রিপোর্ট করা হয়েছে', en: 'Reported' },
  step_attempt: { bn: 'মেরামত চলছে', en: 'Repair Attempt' },
  step_verify: { bn: 'যাচাই চলছে', en: 'Verifying' },
  step_closed: { bn: 'সম্পন্ন', en: 'Closed' },
  credits: { bn: 'ক্রেডিট', en: 'Credits' },
  autoResolve: { bn: 'পর্যাপ্ত যাচাই হলে এটি স্বয়ংক্রিয়ভাবে সম্পন্ন হিসেবে গণ্য হবে।', en: 'Will auto-resolve after sufficient verification.' },
  uploadProof: { bn: 'প্রমাণ আপলোড করুন', en: 'Upload Proof' },
  describeFix: { bn: 'কাজের বিবরণ দিন', en: 'Describe the fix' },
  submitFix: { bn: 'জমা দিন', en: 'Submit Fix' },
  rewardClaim: { bn: 'রিওয়ার্ড', en: 'Reward' },
  ethicsReminder: { bn: 'নৈতিক স্মরণ', en: 'Ethics Reminder' },
  ethicsQuote: { bn: 'আল্লাহ তাআলা আমানত ঠিকভাবে আদায় করার নির্দেশ দিয়েছেন। (ভাবার্থ)', en: 'Indeed, Allah commands you to render trusts to whom they are due. (Quran 4:58)' },
  digitalOath: { bn: 'ডিজিটাল শপথ', en: 'Digital Oath' },
  oathPageTitle: { bn: 'নৈতিক ও নাগরিক শপথ', en: 'Ethical & Civic Oath' },
  rel_islam: { bn: 'ইসলাম', en: 'Islam' },
  rel_hindu: { bn: 'হিন্দু', en: 'Hindu' },
  rel_christian: { bn: 'খ্রিস্টান', en: 'Christian' },
  rel_buddhist: { bn: 'বৌদ্ধ', en: 'Buddhist' },
  rel_secular: { bn: 'সাধারণ', en: 'Secular' },
  text_islam: { bn: 'আমি আল্লাহ্‌র নামে শপথ করছি যে, আমি সর্বদা সত্য বলব, কারও হক নষ্ট করব না এবং এই প্ল্যাটফর্মটি শুধুমাত্র ন্যায় ও কল্যাণের জন্য ব্যবহার করব।', en: 'I swear by Allah that I will speak the truth, fulfill the rights of others, and use this platform only for justice and welfare.' },
  text_hindu: { bn: 'আমি ঈশ্বরের নামে শপথ করছি যে, আমি ধর্ম ও সত্যের পথে থাকব, মিথ্যা পরিহার করব এবং সমাজের মঙ্গলে কাজ করব।', en: 'I swear by God to follow the path of Dharma and Truth, avoid falsehood, and work for the welfare of society.' },
  text_christian: { bn: 'আমি ঈশ্বরের নামে প্রতিজ্ঞা করছি যে, আমি সততার সাথে আমার নাগরিক দায়িত্ব পালন করব এবং প্রতিবেশী ও সমাজের প্রতি বিশ্বস্ত থাকব।', en: 'I pledge before God to fulfill my civic duties with honesty and remain faithful to my neighbors and society.' },
  text_buddhist: { bn: 'আমি বুদ্ধের শিক্ষা স্মরণ করে প্রতিজ্ঞা করছি যে, আমি মিথ্যা ভাষণ থেকে বিরত থাকব এবং সকল প্রাণীর মঙ্গলে কাজ করব।', en: 'Remembering the teachings of Buddha, I pledge to refrain from false speech and work for the welfare of all beings.' },
  text_secular: { bn: 'আমি দেশের একজন দায়িত্বশীল নাগরিক হিসেবে শপথ করছি যে, আমি সংবিধানের প্রতি শ্রদ্ধাশীল থাকব এবং সততা ও নিষ্ঠার সাথে আমার নাগরিক দায়িত্ব পালন করব।', en: 'As a responsible citizen, I pledge to uphold the constitution and perform my civic duties with honesty and integrity.' },
  acceptOath: { bn: 'আমি এই শপথ গ্রহণ করছি', en: 'I accept this oath' },
  confirmOath: { bn: 'শপথ নিশ্চিত করুন', en: 'Confirm Oath' },
  oathAccepted: { bn: 'শপথ গ্রহণ সম্পন্ন হয়েছে', en: 'Oath Accepted' },
  acceptedOn: { bn: 'আপনি এই শপথ গ্রহণ করেছেন:', en: 'You accepted this oath on:' },
  backToHome: { bn: 'হোম এ ফিরে যান', en: 'Back to Home' },
  evidence_analysis: { bn: 'প্রমাণ বিশ্লেষণ', en: 'Evidence Analysis' },
  credibility_score: { bn: 'বিশ্বাসযোগ্যতা স্কোর', en: 'Credibility Score' },
  forensic_result: { bn: 'AI ফরেনসিক ফলাফল', en: 'AI Forensic Result' },
  tampering_risk: { bn: 'কারসাজির ঝুঁকি', en: 'Tampering Risk' },
  chain_custody: { bn: 'চেইন অফ কাস্টডি', en: 'Chain of Custody' },
  result_authentic: { bn: 'অকৃত্রিম (Authentic)', en: 'Authentic' },
  result_edited: { bn: 'সম্পাদিত হতে পারে', en: 'Possibly Edited' },
  result_unclear: { bn: 'অস্পষ্ট', en: 'Unclear' },
  ev_risk_low: { bn: 'কম', en: 'Low' },
  ev_risk_medium: { bn: 'মাঝারি', en: 'Medium' },
  ev_risk_high: { bn: 'উচ্চ', en: 'High' },
  ev_status_verified: { bn: 'যাচাইকৃত', en: 'Verified' },
  ev_status_pending: { bn: 'অপেক্ষমান', en: 'Pending' },
  override_note: { bn: 'অ্যাডমিন নোট যুক্ত করুন', en: 'Add Override Note' },
  mark_suspicious: { bn: 'সন্দেহজনক চিহ্নিত করুন', en: 'Mark Suspicious' },
  mark_verified: { bn: 'যাচাই করুন', en: 'Mark Verified' },
  upload_freshness: { bn: 'আপলোডের সময়', en: 'Freshness' },
  meta_analysis: { bn: 'মেটাডেটা বিশ্লেষণ', en: 'Metadata Analysis' },
  budget_tracker: { bn: 'বাজেট এবং বাস্তবায়ন ট্র্যাকার', en: 'Budget Execution Tracker' },
  approved_budget: { bn: 'অনুমোদিত বাজেট', en: 'Approved Budget' },
  ai_estimate: { bn: 'AI প্রাক্কলন', en: 'AI Estimate' },
  spent_so_far: { bn: 'এ পর্যন্ত ব্যয়', en: 'Spent So Far' },
  remaining: { bn: 'অবশিষ্ট', en: 'Remaining' },
  delay_risk: { bn: 'বিলম্বের ঝুঁকি', en: 'Delay Risk' },
  overrun_alert: { bn: 'খরচ অনুমানের চেয়ে বেশি হচ্ছে', en: 'Cost Overrun Alert' },
  milestones: { bn: 'মাইলফলক', en: 'Milestones' },
  phase: { bn: 'ধাপ', en: 'Phase' },
  planned_cost: { bn: 'পরিকল্পিত ব্যয়', en: 'Planned Cost' },
  actual_cost: { bn: 'প্রকৃত ব্যয়', en: 'Actual Cost' },
  follow_project: { bn: 'এই প্রকল্পটি ফলো করুন', en: 'Follow This Project' },
  planned: { bn: 'পরিকল্পিত', en: 'Planned' },
  actual: { bn: 'প্রকৃত', en: 'Actual' },
  procurement_docs: { bn: 'ক্রয় নথিপত্র', en: 'Procurement Documents' },
  tender_timeline: { bn: 'টেন্ডার টাইমলাইন', en: 'Tender Timeline' },
  doc_type: { bn: 'নথির ধরন', en: 'Document Type' },
  upload_date: { bn: 'আপলোডের তারিখ', en: 'Upload Date' },
  version: { bn: 'সংস্করণ', en: 'Version' },
  access_public: { bn: 'পাবলিক', en: 'Public' },
  access_restricted: { bn: 'সংরক্ষিত', en: 'Restricted' },
  hash: { bn: 'হ্যাশ', en: 'Hash' },
  uploaded_by: { bn: 'আপলোডকারী', en: 'Uploaded By' },
  procurement_cycle: { bn: 'ক্রয় চক্র', en: 'Procurement Cycle' },
  stage_notice: { bn: 'বিজ্ঞপ্তি', en: 'Notice' },
  stage_bidding: { bn: 'বিডিং', en: 'Bidding' },
  stage_evaluation: { bn: 'মূল্যায়ন', en: 'Evaluation' },
  stage_award: { bn: 'পুরস্কার', en: 'Award' },
  view_doc: { bn: 'দেখুন', en: 'View' },
  official_archive: { bn: 'অফিসিয়াল আর্কাইভ', en: 'Official Archive' },
};

export const CITIZEN_NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', labelBn: 'ফিড ও রিপোর্ট', labelEn: 'Feed & Reports', path: '/app', icon: Home },
  { id: 'analytics', labelBn: 'ড্যাশবোর্ড', labelEn: 'Dashboard', path: '/app/analytics', icon: BarChart2 },
  { id: 'notifications', labelBn: 'নোটিফিকেশন', labelEn: 'Notifications', path: '/app/notifications', icon: Bell },
  { id: 'govt', labelBn: 'প্রকল্প ও প্রস্তাবনা', labelEn: 'Projects & Proposals', path: '/app/govt-projects', icon: Building2 },
  { id: 'ministries', labelBn: 'মন্ত্রণালয় স্বচ্ছতা', labelEn: 'Ministry Transparency', path: '/app/ministries', icon: Landmark },
  { id: 'rti', labelBn: 'তথ্য অনুরোধ (RTI)', labelEn: 'RTI Request', path: '/app/rti', icon: FileQuestion },
  { id: 'tenders', labelBn: 'টেন্ডার বিশ্লেষণ', labelEn: 'Tender Analysis', path: '/app/tenders', icon: Briefcase },
  { id: 'integrity', labelBn: 'সততা সূচক', labelEn: 'Integrity Index', path: '/app/integrity', icon: Scale },
  { id: 'hospitals', labelBn: 'হাসপাতাল', labelEn: 'Hospitals', path: '/app/hospitals', icon: Stethoscope },
  { id: 'repair', labelBn: 'কমিউনিটি মেরামত', labelEn: 'Repair', path: '/app/repair', icon: Wrench },
  { id: 'oath', labelBn: 'ডিজিটাল শপথ', labelEn: 'Digital Oath', path: '/app/digital-oath', icon: ScrollText },
];

export const ADMIN_NAV_ITEMS: NavItem[] = [
  { id: 'admin_dashboard', labelBn: 'ড্যাশবোর্ড', labelEn: 'Dashboard', path: '/admin', icon: LayoutDashboard },
  { id: 'admin_crisis', labelBn: 'জরুরি নিয়ন্ত্রণ', labelEn: 'Crisis Control', path: '/admin/crisis-mode', icon: Siren },
  { id: 'admin_moderation', labelBn: 'মডারেশন কিউ', labelEn: 'Moderation Queue', path: '/admin/moderation', icon: ShieldAlert },
  { id: 'admin_reports', labelBn: 'রিপোর্ট পর্যালোচনা', labelEn: 'Report Review', path: '/admin/reports', icon: FileCheck },
  { id: 'admin_rti', labelBn: 'RTI ব্যবস্থাপনা', labelEn: 'RTI Management', path: '/admin/rti', icon: FileQuestion },
  { id: 'admin_evidence', labelBn: 'প্রমাণ ভল্ট', labelEn: 'Evidence Vault', path: '/admin/evidence', icon: Archive },
  { id: 'admin_anomalies', labelBn: 'ভোট অসঙ্গতি', labelEn: 'Vote Anomalies', path: '/admin/anomalies', icon: AlertOctagon },
  { id: 'admin_bots', labelBn: 'বট কার্যকলাপ', labelEn: 'Bot Activity', path: '/admin/bots', icon: Bot },
  { id: 'admin_approvals', labelBn: 'প্রকল্প অনুমোদন', labelEn: 'Project Approvals', path: '/admin/approvals', icon: FileText },
  { id: 'admin_tenders', labelBn: 'টেন্ডার তদারকি', labelEn: 'Tender Oversight', path: '/admin/tenders', icon: Briefcase },
  { id: 'admin_districts', labelBn: 'জেলা নিয়ন্ত্রণ', labelEn: 'District Controls', path: '/admin/districts', icon: Map },
  { id: 'admin_audit', labelBn: 'অডিট লগ', labelEn: 'Audit Logs', path: '/admin/audit-logs', icon: FileClock },
  { id: 'admin_court', labelBn: 'আদালতের আদেশ', labelEn: 'Court Orders', path: '/admin/court-orders', icon: Gavel },
  { id: 'admin_identity', labelBn: 'পরিচয় অনুরোধ', labelEn: 'Identity Requests', path: '/admin/identity-unlock', icon: Unlock },
];

export const NAV_ITEMS = [...CITIZEN_NAV_ITEMS, ...ADMIN_NAV_ITEMS];
